[package]
name = "grit"
version = "0.1.0"
edition = "2021"

[dependencies]
base16ct = { version = "0.2.0", features = ["alloc"] }
clap = { version = "4.5.4", features = ["derive"] }
flate2 = "1.0.30"
libc = "0.2"
sha1 = "0.10.6"
thiserror = "1.0.61"
